# Generated by Django 3.2.19 on 2023-07-27 15:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("a4comments", "0013_set_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="AiReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name="Modified"
                    ),
                ),
                ("is_pending", models.BooleanField(default=True)),
                ("category", models.CharField(max_length=50)),
                ("explanation", models.TextField()),
                ("confidence", models.FloatField(default=0)),
                (
                    "comment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_report",
                        to="a4comments.comment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
