# Generated by Django 3.2.19 on 2023-09-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aireport",
            name="show_in_discussion",
            field=models.BooleanField(default=True),
        ),
    ]
