# Generated by Django 3.2.19 on 2024-06-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_reports", "0002_aireport_show_in_discussion"),
    ]

    operations = [
        migrations.AddField(
            model_name="aireport",
            name="confidence_json",
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="aireport",
            name="explanation_json",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="aireport",
            name="label",
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
