# Generated by Django 3.2.19 on 2024-06-03 14:18
import json

from django.db import migrations


def migrate_to_json(apps, schema_editor):
    AiReport = apps.get_model("ai_reports", "AiReport")

    for report in AiReport.objects.all():
        report.label = [report.category]
        report.confidence_json = [report.confidence]
        report.explanation_json = {report.category: report.explanation}
        report.save()


class Migration(migrations.Migration):
    dependencies = [
        ("ai_reports", "0003_auto_20240603_1643"),
    ]

    operations = [
        migrations.RunPython(
            code=migrate_to_json, reverse_code=migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name="aireport",
            name="category",
        ),
        migrations.RemoveField(
            model_name="aireport",
            name="explanation",
        ),
        migrations.RemoveField(
            model_name="aireport",
            name="confidence",
        ),
    ]
