# Generated by Django 4.2.13 on 2024-09-17 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("a4_candy_cms_settings", "0007_importantpages_registration"),
    ]

    operations = [
        migrations.AddField(
            model_name="importantpages",
            name="faq",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="important_page_faq",
                to="wagtailcore.page",
            ),
        ),
    ]
